### ISSUE TITLE
Front-end work for subtasks

### ISSUE THREAD

**Issue by lilyosah** [Quill-ToDo/App#47]
# Partials

- [ ] Decide for task sections like upcoming and overdue whether we want all sub-tasks and due dates to be listed separately like in the two section component or want them all combined into one list ordered by date (will eventually add other sorting when we add groups). We could also add the option to switch between the two views! I like that more. So a button to switch between the due and work sections and listing all of the tasks in one list ordered by date.
   - [ ] For one list: Make sure sub-tasks/to work on are represented by circle check-marks. 
   - [ ] For things that are due, make sure they use the square check-marks but also maybe add "due" after the task name to further make it clear that these are due dates. 
   
# Calendar

## Decide how you want to add sub-tasks based on the calendar view.

Ideas: 
- Hovering over the task on one day, a circle (slightly transparent) pops up in the middle of the line after 2-3 seconds and if you click then, a task creation box will pop up with the title "work on [task name]" already filled out (the entire pre-filled text can be changed by the user). When they submit, the circle is added to that day. When they complete the sub-task, the circle is filled? A check-mark is added?
- Hovering over the task line in the (horizontal) middle of the day div makes the circle appear

## Decide how we want multiple sub-tasks on one day/sub-task and due on one day represented

Ideas:
- Only allow one sub-task to be added per day, but you can add a checklist to a sub-task (using markdown). A number of how many check-boxes are added to one sub-task is displayed within the circle on the list and calendar view. Maybe we should do something similar for the due date task? Like sub-tasks are displayed in a list within the task show somehow and the number of uncompleted sub-tasks is displayed inside the check box? Or at least somewhere.
- Add multiple sub-tasks per day, maybe show some sort of stack of circle boxes on the calendar that when you hover over, expands to a little line below it or something.
